language: java
arch:
  - amd64
  - ppc64le
jdk: openjdk11
script:
  - ./gradlew --no-daemon clean javadoc
  - ./gradlew --max-workers=1 --no-daemon analyze
  - ./gradlew --no-daemon -PmaxParallelForks=1 build
